import { Student, ClassNote, FollowUp } from './types';

export const mockStudents: Student[] = [
  {
    id: 'ST-8821',
    name: 'Rahul Sharma',
    initials: 'RS',
    grade: 'ICSE Grade 10',
    parentName: 'Rajesh Sharma',
    parentPhone: '+91 98201 54321',
    course: 'Physics & Chemistry',
    schedule: '3x weekly (Mon, Wed, Fri)',
    teacher: 'Amit Sharma',
    status: 'Active',
    nextFollowUp: 'Overdue (Yesterday)',
    followUpStatus: 'overdue',
    attendance: 92,
    avatarColor: 'bg-indigo-100 text-indigo-700',
  },
  {
    id: 'ST-8822',
    name: 'Priya Shah',
    initials: 'PS',
    grade: 'CBSE Grade 12',
    parentName: 'Neha Shah',
    parentPhone: '+91 98112 33445',
    course: 'Higher Mathematics',
    schedule: 'Calculus & Vectors',
    teacher: 'Amit Sharma',
    status: 'Active',
    nextFollowUp: 'Today, 10:30 AM',
    followUpStatus: 'today',
    attendance: 80,
    avatarColor: 'bg-indigo-100 text-indigo-700',
  },
  {
    id: 'ST-8823',
    name: 'Aarav Mehta',
    initials: 'AM',
    grade: 'CBSE Grade 9',
    parentName: 'Vikram Mehta',
    parentPhone: '+91 98765 43210',
    course: 'Math Foundation',
    schedule: 'Geometry & Algebra',
    teacher: 'Amit Sharma',
    status: 'Active',
    nextFollowUp: 'Today, 2:00 PM',
    followUpStatus: 'today',
    attendance: 95,
    avatarColor: 'bg-indigo-100 text-indigo-700',
  },
  {
    id: 'ST-8824',
    name: 'Tanvi Deshmukh',
    initials: 'TD',
    grade: 'IGCSE Grade 10',
    parentName: 'Sunil Deshmukh',
    parentPhone: '+91 99887 66554',
    course: 'Mathematics Extended',
    schedule: 'Trial Class Pending',
    teacher: 'Amit Sharma',
    status: 'Lead',
    nextFollowUp: 'Oct 26 (In 2 days)',
    followUpStatus: 'none',
    attendance: 0,
    avatarColor: 'bg-slate-100 text-slate-700',
  },
  {
    id: 'ST-8825',
    name: 'Kabir Singhania',
    initials: 'KS',
    grade: 'Grade 11',
    parentName: 'Pooja Singhania',
    parentPhone: '+91 91234 56789',
    course: 'Applied Physics',
    schedule: 'Mechanics & Waves',
    teacher: 'Amit Sharma',
    status: 'Active',
    nextFollowUp: 'All caught up',
    followUpStatus: 'caught-up',
    attendance: 100,
    avatarColor: 'bg-indigo-100 text-indigo-700',
  },
];

export const mockClassNotes: ClassNote[] = [
  {
    id: 'CN-1',
    date: 'Oct 23, 2024',
    time: '5:00 PM - 6:00 PM',
    subject: 'Physics',
    topic: 'Light - Reflection & Spherical Mirrors',
    understanding: 'Good Understanding',
    covered: 'Finished mirror formula derivations, worked through 4 ray diagram practice problems. Explained Cartesian sign conventions for concave and convex mirrors.',
    homework: 'Exercise 4.2 questions 1-8; re-draw concave mirror ray table without looking at reference textbook.',
    tutorNote: 'Rahul grasped the sign convention well today. Needs slight speed improvement on math calculation with fractions. No calculator permitted in ICSE 10th.',
    followUpCreated: true,
  },
  {
    id: 'CN-2',
    date: 'Oct 19, 2024',
    time: '5:00 PM - 6:00 PM',
    subject: 'Physics',
    topic: 'Refraction Index & Snell\'s Law',
    understanding: 'Needs Practice',
    covered: 'Introduced refractive index concept, absolute vs relative indices, and trigonometric ratios for Snell\'s law ($n_1 \\sin \\theta_1 = n_2 \\sin \\theta_2$).',
    homework: 'Revise Snell\'s Law formula and solve sample paper set 1 (Questions 5 to 12).',
  },
  {
    id: 'CN-3',
    date: 'Oct 12, 2024',
    time: '5:00 PM - 6:00 PM',
    subject: 'Physics',
    topic: 'Electric Current Basics & Ohm\'s Law',
    understanding: 'Excellent',
    covered: 'Conducted complete review of potential difference, Ohm\'s law, and V-I characteristic curves. Solved numerical problems on series and parallel circuits.',
    homework: 'Review notes.',
  },
];

export const mockFollowUps: FollowUp[] = [
  {
    id: 'FU-1',
    title: 'Confirm Saturday Reschedule & HW',
    description: 'Confirm reschedule for missed Saturday class & check homework submission for Chapter 4.',
    dueDate: 'Yesterday, 4:00 PM',
    contactMethod: 'WhatsApp',
    contactDetail: '+91 98201 54321',
    isOverdue: true,
  }
];
